### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by Tristan0430** [spider-rs/spider-py#1]
Collecting spider_rs
  Using cached http://mirrors.aliyun.com/pypi/packages/26/ba/bc4bf77e7923583aede0ed4a203f2ea5c2d6a2c85fe8d07f4b3f81570c9b/spider_rs-0.0.30.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
          Updating `rsproxy` index
      From https://rsproxy.cn/crates.io-index
       * [new ref]         HEAD       -> origin/HEAD
      error: failed to select a version for the requirement `spider = "^1.86.11"` (locked to 1.86.11)
      candidate versions found which didn't match: 1.86.5, 1.86.4, 1.86.3, ...
      location searched: `rsproxy` index (which is replacing registry `crates-io`)
      required by package `spider_rs v0.0.30 (C:\Users\m1778\AppData\Local\Temp\pip-install-v_9bx8vo\spider-rs_d3f1942900e14bb9966f68dbe963a045)`
      perhaps a crate was updated and forgotten to be re-vendored?
      馃挜 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\m1778\\AppData\\Local\\Temp\\pip-modern-metadata-pzhkjv6h', '--interpreter', 'C:\\Users\\m1778\\.pyenv\\pyenv-win\\versions\\3.11.6\\python.exe']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:\Users\m1778\AppData\Local\Temp\pip-modern-metadata-pzhkjv6h --interpreter C:\Users\m1778\.pyenv\pyenv-win\versions\3.11.6\python.exe`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by j-mendez** [comment]
Hi can you try `0.0.31`? There was an update with `maturin` messed up some of the compilation of the cargo crate metadata like being able to add a 'description' etc. This recently just started happening.

**Comment by j-mendez** [comment]
```sh
pip install spider_rs 
Collecting spider_rs
  Downloading spider_rs-0.0.31.tar.gz (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.2/40.2 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: spider_rs
  Building wheel for spider_rs (pyproject.toml) ... done
  Created wheel for spider_rs: filename=spider_rs-0.0.31-cp311-cp311-macosx_11_0_arm64.whl size=7828504 sha256=c3ec7eb5f5f60fc543f2f509f91f9bca1a7d4622456df2ebfd7a550b60593f5a
  Stored in directory: /Users/jmendez/Library/Caches/pip/wheels/53/46/f1/5045ed476b19aef1626e769090fb9707c541ed3da4eac50950
Successfully built spider_rs
Installing collected packages: spider_rs
Successfully installed spider_rs-0.0.31
```
0.0.31 works on mac, I need to spin up a windows vm to test later.

**Comment by Tristan0430** [comment]
thx，I just installed `0.0.33` successfully.
